services:
  dev:
    image: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    depends_on:
      - nats-init
    volumes:
      - ..:/workspaces:cached
      - nats-auth:/etc/nats-auth
    # Port forwarded for local development with emacs tramp
    # ports:
    #   - "127.0.0.1:2222:2222"
    # Use "forwardPorts" in **devcontainer.json** to forward a port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  haproxy:
    build:
      context: .
      dockerfile: Dockerfile.haproxy
    network_mode: service:dev

  nats-auth:
    image: natsio/nats-box:0.13.8
    command:
      - /tmp/configure-nats
    volumes:
      - nats-auth:/etc/nats-auth
      - ./setup-scripts:/tmp

  nats:
    image: nats:alpine
    restart: unless-stopped
    command:
      - --jetstream
      - -c
      - /etc/nats/resolver.conf
      - -D
    depends_on:
      - nats-auth
    volumes:
      - nats-auth:/etc/nats

  nats-init:
    image: devcontainer
    depends_on:
      - nats
    restart: on-failure
    command:
      [
        "nats",
        "stream",
        "--server=nats",
        "add",
        "loadbalancer-manager-haproxy",
        "--subjects=com.infratographer.>",
        "--storage=memory",
        "--replicas=1",
        "--retention=limits",
        "--discard=old",
        "--max-msgs=-1",
        "--max-msgs-per-subject=-1",
        "--max-bytes=-1",
        "--max-age=-1",
        "--max-msg-size=-1",
        "--dupe-window='2m0s'",
        "--no-allow-rollup",
        "--deny-delete",
        "--deny-purge"
      ]

volumes:
  nats-auth:
